name: salloon_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #TODO: Handle Success and Failure
  dartz: ^0.10.1

  # TODO: Compare to States and Objects
  equatable: ^2.0.5

  #TODO: Animation
  animate_do: ^3.1.2

  #TODO: State Management
  flutter_bloc: ^8.1.3

  #TODO: Dependencies Injection
  get_it: ^7.6.4

  #TODO: Googele Fonts
  google_fonts: ^6.1.0

  #TODO: Custom Calender
  table_calendar: ^3.0.9

  #TODO: for Firebase
  firebase_core: ^2.13.0
  firebase_storage: ^11.2.1
  cloud_firestore: ^4.7.1
  firebase_auth: ^4.6.1

  #TODO: googel_login
  google_sign_in: ^6.1.1
  razorpay_web: ^1.4.2
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Visby
      fonts:
        - asset: assets/fonts/VisbyBold.otf
        - asset: assets/fonts/VisbyLight.otf
        - asset: assets/fonts/VisbyMedium.otf
        - asset: assets/fonts/VisbyRegular.otf
        - asset: assets/fonts/VisbySemibold.otf
