// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzXRfNAicSbRJ5GkXIqYxn3GsFFLOw-BU',
    appId: '1:753458621289:web:265cdc68a425c98b4b6bf8',
    messagingSenderId: '753458621289',
    projectId: 'saloon-app-df02f',
    authDomain: 'saloon-app-df02f.firebaseapp.com',
    storageBucket: 'saloon-app-df02f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXeMbqv0JOqm_92_Z0QQLCJ7hl_7U9ezE',
    appId: '1:753458621289:android:02c74469eac5be124b6bf8',
    messagingSenderId: '753458621289',
    projectId: 'saloon-app-df02f',
    storageBucket: 'saloon-app-df02f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3Thgiyrsdh6xBfBrE8t7POFdA2JU4Z1Q',
    appId: '1:753458621289:ios:83a6df06d4482a7a4b6bf8',
    messagingSenderId: '753458621289',
    projectId: 'saloon-app-df02f',
    storageBucket: 'saloon-app-df02f.appspot.com',
    iosBundleId: 'com.example.salloonApp',
  );
}
